<?php
/**
 *
 * The content is generated by using TextMate, and edited by yuhari.
 *
 *
 * 生命周期After 功能
 *
 *
 * @author 	   yuhari
 * @maintainer yuhari
 * @version    1.0.0
 * @modified   2019/08/09 18:48:25
 *
 */

namespace Util\Annotations ;

/**
 * @Annotation
 * @Target("CLASS","METHOD")
 */
class After extends Annotation {
	
} // END final class 