<?php
/**
 *
 * The content is generated by using TextMate, and edited by yuhari.
 *
 *
 * 生命周期Before 功能
 * 975207337
 * @author 	   yuhari
 * @maintainer yuhari
 * @version    1.0.0
 * @modified   2019/08/09 18:49:02
 *
 */

namespace Util\Annotations ;

/**
 *
 * @Annotation
 * @Target("CLASS", "METHOD")
 */
class Before extends Annotation {
	
	
} // END final class 