<?php
/**
 *
 * The content is generated by using TextMate, and edited by yuhari.
 *
 *
 * 启动载入注释
 *
 * @author 	   yuhari
 * @maintainer yuhari
 * @version    1.0.0
 * @modified   2019/08/09 18:49:26
 *
 */

namespace Util\Annotations ;

use Doctrine\Common\Annotations\Annotation\Required; 
use Doctrine\Common\Annotations\Annotation\Enum; 

/**
 *
 * @Annotation
 * @Target({"METHOD", "CLASS"})
 */
class Bootstrap extends Annotation {
	
	public $_target ;
} // END final class 