<?php
/**
 *
 * The content is generated by using TextMate, and edited by yuhari.
 *
 *
 * 注释异常
 *
 *
 * @author 	   yuhari
 * @maintainer yuhari
 * @version    1.0.0
 * @modified   2019/08/12 14:01:25
 *
 */
namespace Util\Exceptions ;

class AnnotationException extends \Exception {
	
}
