<?php
/**
 *
 * The content is generated by using TextMate, and edited by yuhari.
 *
 *
 * 注释容器异常
 *
 *
 * @author 	   yuhari
 * @maintainer yuhari
 * @version    1.0.0
 * @modified   2019/08/12 14:25:13
 *
 */
namespace Util\Exceptions ;

class AnnotationContainerException extends \Exception {
	
	
}
